"""Add optional to type in categories

Revision ID: 3c03bf43ffbb
Revises: c80ddc498964
Create Date: 2025-06-16 18:00:51.817970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c03bf43ffbb'
down_revision: Union[str, None] = 'c80ddc498964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Categories', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Categories', 'type')
    # ### end Alembic commands ###
